# Jekyll configuration for GitHub Pages
theme: jekyll-theme-cayman
title: CallFlow Tracer
description: A comprehensive Python library for tracing, profiling, and visualizing function call flows
baseurl: "/callflow-tracer"
url: "https://rajveer43.github.io"

# Navigation
navigation:
  - title: Home
    url: /
  - title: Installation
    url: /INSTALLATION_GUIDE
  - title: User Guide
    url: /USER_GUIDE
  - title: API Reference
    url: /API_DOCUMENTATION
  - title: Features
    url: /FEATURES_COMPLETE
  - title: GitHub
    url: https://github.com/rajveer43/callflow-tracer

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Plugins
plugins:
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-titles-from-headings

# Settings
relative_links:
  enabled: true
  collections: true

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _site
